name: builder

on:
  workflow_call:
    inputs:
      prebuild: 
        type: string    
      project-name: 
        type: string
      repo: 
        type: string
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true
      VERCEL_TOKEN:
        description: 'Vercel API token, account level'
        required: true
      VERCEL_ORG_ID:
        description: 'Vercel ORG token, org level'
        required: true
      VERCEL_PROJECT_ID_DOCS_DEV:
        description: 'Vercel PROJECT token, project level (deprecated)'
      VERCEL_PROJECT_ID_DEV_PREVIEW_DOCS:
        description: 'Vercel PROJECT token, project level'        

jobs:
  preview:
    name: doc builder
    runs-on: ubuntu-latest
    steps:

      - name: Setup workspace
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get ref
        id: get_ref
        uses: actions/github-script@v7
        with:
          script: |
            let ref = `${{ github.event.merge_group.head_ref }}`;
            if (!ref) {
              ref = `refs/pull/${{ github.event.number }}/head`
            }
            core.setOutput('ref', ref);

      - name: Checkout branch into temp
        if: github.event.action != 'closed' && github.event.pull_request.merged != true
        uses: actions/checkout@v4
        with:
          path: 'tmp'
          fetch-depth: 2
          ref: ${{ steps.get_ref.outputs.ref }}
          persist-credentials: false

      - name: Prepare content for deploy
        if: ${{ github.event.pull_request.merged }}
        uses: actions/checkout@v4
        with:
          path: 'tmp'
          persist-credentials: false

      - name: Checkout dev doc docsmobile app
        uses: actions/checkout@v4
        with:
          repository: elastic/docs.elastic.dev
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/docs.elastic.dev
          persist-credentials: false

      - name: Checkout Wordlake
        uses: actions/checkout@v4
        with:
          repository: elastic/wordlake-dev
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/wordlake-dev

      - name: Temp sources override
        shell: bash
        run: cp -f ${{ github.workspace }}/wordlake-dev/.scaffold/content.js ${{ github.workspace }}/docs.elastic.dev/config/.

      - name: Portal
        if: github.event.action != 'closed' || github.event.pull_request.merged == true
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/wordlake-dev/${{ github.event.repository.name }}
          rm -rf ${{ github.workspace }}/wordlake-dev/${{ github.event.repository.name }}/*
          rsync --ignore-missing-args -zavpm --no-l \
          --exclude='cats.mdx' \
          --exclude='infrastructure/ansible/systests/*' \
          --include='*.docnav.json' \
          --include='*.apidocs.json' \
          --include='*.mdx' \
          --include='*.png' \
          --include='*.gif' \
          --include='*.jpg' \
          --include='*.svg' \
          --include='*.jpeg' \
          --include='*.webp' \
          --include='*.devdocs.json' \
          --include='*/' \
          --exclude='*' \
          ${{ github.workspace }}/tmp/ \
          ${{ github.workspace }}/wordlake-dev/${{ github.event.repository.name }}/

      - name: Tidy before Vercel CLI run
        if: github.event.pull_request.merged != true && github.event.pull_request.closed != true
        shell: bash
        run: |
            mkdir ${{ github.workspace }}/build/ 
            mv ${{ github.workspace }}/wordlake-dev ${{ github.workspace }}/build/
            mv ${{ github.workspace }}/docs.elastic.dev ${{ github.workspace }}/build/

      - name: Generate preview
        if: github.event.pull_request.merged != true && github.event.pull_request.closed != true
        id: vercel-deploy
        uses: elastic/builder@v25.2.0
        continue-on-error: false
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DOCS_DEV || secrets.VERCEL_PROJECT_ID_DEV_PREVIEW_DOCS }} #Fallback in place for migration
          vercel-project-name: ${{ inputs.project-name || 'dev-preview-docs' }} #Fallback in place for migration
          working-directory: ${{ github.workspace }}/build/
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }} #Optional 
          github-comment: true # Otherwise need github-token (VERCEL_GITHUB_TOKEN)

      - name: Portal for deploy
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == github.event.pull_request.base.repo.default_branch
        shell: bash
        run: |
          cd ${{ github.workspace }}/wordlake-dev
          git config user.name elasticdocs
          git config user.email docs-eng+elasticdocs@elastic.co
          git pull
          git add .
          git commit -m "New content from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          git push https://${{ secrets.VERCEL_GITHUB_TOKEN }}@github.com/elastic/wordlake-dev
